theme: jekyll-theme-cayman

title: Krister Jazz Urog
description: Research Interests:

Bioinformatics - Complex Systems - Software Developnment - Data Science

github:
  repository_url: https://github.com/KristerJazz
